[scripts] added passive-agressive punctuation in error messages

diff --git a/scripts/.local/bin/update-restow b/scripts/.local/bin/update-restow
--- a/scripts/.local/bin/update-restow
+++ b/scripts/.local/bin/update-restow
@@ -1,7 +1,7 @@
 #!/bin/sh
 
  command -v yay >/dev/null 2>&1 || {
-        echo "yay executable not found"
+        echo "yay executable not found."
         exit 1
 }
 
@@ -12,7 +12,7 @@ while true; do
         case $yn in
                 [Yy]* ) 
                         command -v stow >/dev/null 2>&1 || {
-                                echo "Stow executable not found"; exit 1
+                                echo "Stow executable not found."; exit 1
                         }
 
                         cd "$HOME/.dotfiles" || {
