[scripts] did some reindenting

diff --git a/scripts/.local/bin/update-restow b/scripts/.local/bin/update-restow
--- a/scripts/.local/bin/update-restow
+++ b/scripts/.local/bin/update-restow
@@ -1,30 +1,30 @@
 #!/bin/sh
 
 sudo pacman -Syu || {
-        echo "Some packages couldn't be updated!"
+    echo "Some packages couldn't be updated!"
 }
 
 while true; do
-        printf "\nDo you wish to restow the dotfiles? [Y/n] "
-        IFS= read -r yn
+    printf "\nDo you wish to restow the dotfiles? [Y/n] "
+    IFS= read -r yn
 
-        case $yn in
-                [Nn]* ) exit;;
-                * ) 
-                        command -v stow >/dev/null 2>&1 || {
-                                echo "'stow' executable not found."
-                                exit 1
-                        }
+    case $yn in
+        [Nn]* ) exit;;
+        * ) 
+            command -v stow >/dev/null 2>&1 || {
+                echo "'stow' executable not found."
+                exit 1
+            }
 
-                        cd "$HOME/.dotfiles" || {
-                                echo "Can't find the ~/.dotfiles folder."
-                                exit 1 
-                        }
-                        
-                        for pkg in */; do
-                                stow --restow --ignore "README.md" --verbose 1 "$pkg"
-                        done
+            cd "$HOME/.dotfiles" || {
+                echo "Can't find the ~/.dotfiles folder."
+                exit 1 
+            }
+            
+            for pkg in */; do
+                stow --restow --ignore "README.md" --verbose 1 "$pkg"
+            done
 
-                        break;;
-        esac
+            break;;
+    esac
 done
